# Generated by Django 4.2.13 on 2024-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
