# Generated by Django 4.2.13 on 2024-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='suggested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Maybe', 'Maybe')], default='Pending', max_length=20),
        ),
    ]
