# Generated by Django 4.2.13 on 2024-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_suggested_date_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='suggested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
