# Generated by Django 4.2.13 on 2024-07-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_invitation_suggested_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='suggested_time',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='suggested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
