# Generated by Django 4.2.13 on 2024-07-07 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('invitation_response', 'Invitation Response'), ('event_reminder', 'Event Reminder'), ('suggested_alternate_date', 'Suggested Alternate Date'), ('event_confirmed', 'Event Confirmed')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
