# Generated by Django 4.2.13 on 2024-07-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('invitation_response', 'Invitation Response'), ('suggested_alternate_date', 'Suggested Alternate Date'), ('event_confirmed', 'Event Confirmed'), ('friend_request_received', 'Friend Request Received')], max_length=50),
        ),
    ]
